### ISSUE TITLE
Token refresh

### ISSUE THREAD

**Issue by jdubz666** [vangorra/python_withings_api#23]
Hi,

My token keeps expiring. How do I refresh the token without having to delete the credentials file and allow the app again?

Thank you

**Comment by vangorra** [comment]
The underlying OAuth2 api this module uses will automatically refresh the token when needed. That however only works if you are requesting data regularly. For less frequent requests, I added WithingsApi.refresh_token() so you can manually refresh the token if needed.

**Comment by jdubz666** [comment]
So I was using a scheduled task to run it frequently but the token still expires unfortunately.  

I'm using your new release now with built in refresh. When I run the integration test it errors "WithingsApi object has no attribute 'refresh token'".  Do you know what's stopping Integration_test from running?

Thank you for your help and the lightening fast response!
