### ISSUE TITLE
ValueError: 123 is not a valid MeasureType

### ISSUE THREAD

**Issue by ivale** [vangorra/python_withings_api#26]
Hy I'm trying to get the API working. I got results from integration_test.py but as soon as I ty to get my data and not the mode='demo' I get:  ValueError: 123 is not a valid MeasureType

the cose is

`from urllib import parse

from withings_api import WithingsAuth, WithingsApi, AuthScope
from withings_api.common import get_measure_value, MeasureType

auth = WithingsAuth(
    client_id='myID',
    consumer_secret='myCons',
    callback_uri='https://google.com/',
    scope=(
        AuthScope.USER_ACTIVITY,
        AuthScope.USER_METRICS,
        AuthScope.USER_INFO,
        AuthScope.USER_SLEEP_EVENTS,
    )
)

authorize_url = auth.get_authorize_url()
print("Goto this URL in your browser and authorize:")
print(authorize_url)
redirected_uri = input("Provide the entire redirect uri: ")
redirected_uri_params = dict(
    parse.parse_qsl(parse.urlsplit(redirected_uri).query)
)
auth_code = redirected_uri_params["code"]
print("Getting credentials with auth code", auth_code)
credentials = auth.get_credentials(auth_code)
print(credentials)

api = WithingsApi(credentials)

meas_result = api.measure_get_meas()    <--------------here get the error
weight_or_none = get_measure_value(meas_result, with_measure_type=MeasureType.WEIGHT)
print(meas_result);`

Anyone can help me?
Thanks

**Comment by jdubz666** [comment]
MeasType should be one. I do the post request within the tests. Here's just the portion of the script with the post request, I load it into InfluxDB as well.

**Comment by jdubz666** [comment]
import requests
import json


##########

    res=requests.get("https://wbsapi.withings.net/measure?action=getmeas", headers={"Authorization":"Bearer " + access_token}, params={ "meastype":"1"})


    res_out = json.loads(res.text)

#    print(res_out)

    host = xxxx
    port = xxxx
    user = xxxx
    password = xxxx
    dbname = xxxx

    client = InfluxDBClient(host, port, user, password, dbname)

#    print(res_out['body']['measuregrps']['measures'][0])

    measure1 = res_out['body']['measuregrps']

    x = 0
    for item in measure1:
       withings_date = measure1[x]['date']
       withings_value = round((measure1[x]['measures'][0]['value'])*2.204622622, 1)
       x = x + 1
       json_body = [
        {
              "measurement": "lb",
              "tags": {
                  "entity_id": "withings_weight",
                  "domain":"sensor"
              },
              "time": str(datetime.utcfromtimestamp(withings_date).strftime('%Y-%m-%d')) + "T23:59:00Z",
              "fields": {
                  "value": (withings_value)/1000,
              }
          }

      ]

       client.write_points(json_body)

    pass
    client.close()




if __name__ == "__main__":
    main()

**Comment by jdubz666** [comment]
[influx_weight.txt](https://github.com/vangorra/python_withings_api/files/4451976/influx_weight.txt)

**Comment by vangorra** [comment]
Can you post the full exception?

**Comment by ivale** [comment]
ValueError: 123 is not a valid MeasureType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 74, in <module>
    meas_result = api.measure_get_meas()
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/__init__.py", line 159, in measure_get_meas
    self.request(path=self.PATH_MEASURE, params=params)
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 649, in new_measure_get_meas_response
    for group in data.get("measuregrps", ())
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 649, in <genexpr>
    for group in data.get("measuregrps", ())
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 637, in new_measure_get_meas_group
    for measure in data.get("measures", ())
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 637, in <genexpr>
    for measure in data.get("measures", ())
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 621, in new_measure_get_meas_measure
    type=new_measure_type(data.get("type")),
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 117, in new_measure_type
    return cast(MeasureType, enum_or_raise(value, MeasureType))
  File "/Users/myuser/Desktop/python_withings_api-master/withings_api/common.py", line 403, in enum_or_raise
    return enum(value)
  File "/Users/myuser/.pyenv/versions/3.7.5/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/Users/myuser/.pyenv/versions/3.7.5/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/Users/myuser/.pyenv/versions/3.7.5/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/Users/myuser/.pyenv/versions/3.7.5/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 123 is not a valid MeasureType

**Comment by ivale** [comment]
I updated the library but the same error remains ..

**Comment by vangorra** [comment]
Do you have the json being returned by withings?

**Comment by vangorra** [comment]
Closing stale issues.
