### ISSUE TITLE
Home Assistant integration of "bed in" and "bed out"

### ISSUE THREAD

**Issue by Hooch76** [vangorra/python_withings_api#32]
Hi,

I've just seen that 
https://github.com/vangorra/python_withings_api/blob/master/withings_api/common.py#L131
already contains

```
BED_IN = 50
BED_OUT = 51
```

Any chance that this can be exposed to be used in Home Assistant (https://www.home-assistant.io/integrations/withings/), too?

Thanks,
Tom

**Comment by vangorra** [comment]
Withings pushes bed presence to a publicly accessible webhook running in your server. Getting this to work in HA with take considerable effort as much of the withings code will need to be rewritten.
On that note, I've been working on code that does exactly this. From my perspective, it's code compete but I'm letting it run for a couple days to watch the logs to ensure it works correctly. I'll probably have a PR out for HA next week.

**Comment by vangorra** [comment]
Here's a PR for home assistant that adds support for in bed detection. It's a large PR so it will take a while to get merged. https://github.com/home-assistant/core/pull/34447

**Comment by Hooch76** [comment]
Excellent news. Really appreciate that. Thank you!
