### ISSUE TITLE
Completely clone to adapt to another API

### ISSUE THREAD

**Issue by tikismoke** [vangorra/python_withings_api#33]
Hi,

I wanted to let you know that i clone your repo to adapt it to another API.
It's Xee api v4 that also use Oauth2 like withings.

I'm going to make it working as much as i can.

The goal will be to have a pure python api and made it available in Homeassistant in the future.

Thank's for all your work.

**Comment by vangorra** [comment]
Great! I'm happy to hear this helps somebody. I feel the one of the greatest strengths of this API implementation is it's strict adhearance to immutable design and strong typing. I'm glad that philosophy can help somebody else.
