### ISSUE TITLE
getting sleep data rr & hr

### ISSUE THREAD

**Issue by ssosas** [vangorra/python_withings_api#36]
Hi,
I'm trying to get all sleep data with the method sleep_get(). I mainly want  rr and hr data during the night. I'm using next call:

test_data = self.__api.sleep_get(startdate=arrow.utcnow().shift(days=-1), enddate=arrow.utcnow(), data_fields=GetSleepField )

But no data are retrieved.

If I remove data_fields parameter, I just get sleep levels but rr and hr have "None" values.

Is there any mistake in my call?

Thanks for your support! ;)

**Comment by vangorra** [comment]
`data_fields` expects an iterable like a list or tuple. https://github.com/vangorra/python_withings_api/blob/master/withings_api/__init__.py#L168
