### ISSUE TITLE
device info

### ISSUE THREAD

**Issue by AlexanderAlder** [vangorra/python_withings_api#37]
Would be nice if home assistant could also list my withings device info.
More specifically, I'm interested in the battery status of my body+ scale

**Comment by vangorra** [comment]
That would be a feature request for Home Assistant. This library is independent of Home Assistant.
That being said I also maintain the Home Assistant integration and this will be simple enough.

**Comment by AlexanderAlder** [comment]
Ok, I've submitted 2 requests here: https://community.home-assistant.io/t/withings-integration-extra-features/207252
Thanks

**Comment by vangorra** [comment]
BTW. A device info PR is pending review for Home Assistant here: https://github.com/home-assistant/core/pull/37287
