### ISSUE TITLE
consider change to pydantic

### ISSUE THREAD

**Issue by CircleOnCircles** [vangorra/python_withings_api#47]
I saw a lot of attempts to do validation. 
I saw your love in `arrow` lib. really good taste
`pydantic` might be a good fit to this project.
I can help you migrate.

https://github.com/vangorra/python_withings_api/blob/1c1f36d4fb036acd2e4c8337da46dd4a85d75092/withings_api/common.py#L751-L763

**Comment by CircleOnCircles** [comment]
I thought you are not agree. So,
I've been working on my https://github.com/codustry/python_withings_api/tree/codustry_s for a while.

**Comment by vangorra** [comment]
I'm always happy to remove code to reduce maintenance. I want sure pydandic would work but once I realized it has no dependencies, is type strict and allows for immutable objects, I figured it was worth an attempt.
There was a bit of a learning curve but this worked out nicely.
