### ISSUE TITLE
Withings API Breaking Change - Oauth2 URL - Due by 2021-09-01

### ISSUE THREAD

**Issue by ronaldheft** [vangorra/python_withings_api#65]
Withings announced [a breaking change to their API](https://support.withings.com/hc/en-us/articles/360016745358-Deprecating-access-and-refresh-tokens-endpoints) to take affect on September 1, 2021.

It does not look like this library is compliant with the new URL (using old URL here: https://github.com/vangorra/python_withings_api/blob/master/withings_api/__init__.py#L335).

The new URL is `v2/oauth2`. This will also require some response parsing changes, as the token and other attributes are now nested under `body` in the response.

**Comment by vangorra** [comment]
Fixed in #75
