### ISSUE TITLE
Question: Distinguish weight by user

### ISSUE THREAD

**Issue by jamesgeddes** [vangorra/python_withings_api#69]
My partner and I are both set up on the same Body+ scales. How do I distinguish her measurements from mine? 

I have looked at the [docs](https://developer.withings.com/api-reference#operation/measure-getmeas) and I cannot see how withings advises who logged the measurement. What am I missing here?

**Comment by vangorra** [comment]
Withings distinguishes between people though a separate profile or account. At any rate, it means you must keep a second set of authentication tokens and credentials.

-------- Original Message --------

**Comment by jamesgeddes** [comment]
Using IFTTT, all her measurements are ending up in my Google spreadsheet, so I was wondering if there was a way to Python something.

If I access the API with my keys, will it ignore her measurements and only show me mine?

**Comment by jamesgeddes** [comment]
Thanks!
