### ISSUE TITLE
<MeasureType.UNKNOWN: -999999> - python3.9/site-packages/withings_api/common.py:38

### ISSUE THREAD

**Issue by ChristianH21220** [vangorra/python_withings_api#70]
Hi Robbert, can you pls take a look at:

 Withings Integration Issues #52089 for HA. The setup never finish to create the Webhook

Error: Retrying setup: <MeasureType.UNKNOWN: -999999>
Logger: python_withings_api
Source: /usr/local/lib/python3.9/site-packages/withings_api/common.py:38
 Unsupported <enum 'MeasureType'> value 135. Replacing with UNKNOWN value MeasureType.UNKNOWN. Please report this warning to the developer to ensure proper support.

**Comment by vangorra** [comment]
Fixed in #74
