### ISSUE TITLE
Shutting down access and refresh tokens endpoints

### ISSUE THREAD

**Issue by chpego** [vangorra/python_withings_api#75]
Hi,

I receive this information, from withings

https://support.withings.com/hc/en-us/articles/360016745358-Deprecating-access-and-refresh-tokens-endpoints

There is a deprecated endpoint for authentification

**Comment by mkaatman** [comment]
It looks like it is already pointing at the new oauth endpoint.

https://github.com/vangorra/python_withings_api/blob/master/withings_api/__init__.py#L60

**Comment by nbogojevic** [comment]
II think that one is used for getting health data. 

Authorization code still uses old one:
https://github.com/vangorra/python_withings_api/blob/25b58bf1532a98c169cc25e6205550e211e9e273/withings_api/__init__.py#L337-L340

And it is used in 
https://github.com/vangorra/python_withings_api/blob/25b58bf1532a98c169cc25e6205550e211e9e273/withings_api/__init__.py#L374-L378

https://github.com/vangorra/python_withings_api/blob/25b58bf1532a98c169cc25e6205550e211e9e273/withings_api/__init__.py#L429-L437

Also request output changed, so this:
https://github.com/vangorra/python_withings_api/blob/25b58bf1532a98c169cc25e6205550e211e9e273/withings_api/__init__.py#L385
and this
https://github.com/vangorra/python_withings_api/blob/25b58bf1532a98c169cc25e6205550e211e9e273/withings_api/__init__.py#L458
 
should probably be 
 `**response["body"],`
and
 `self._update_token(token=token_dict["body"]) ,`

I did those changes in my fork https://github.com/nbogojevic/python_withings_api/, going to check tomorrow if that fixes the issue.

**Comment by mkaatman** [comment]
Oh you're correct. Good catch.

**Comment by mkaatman** [comment]
How'd that work out?

**Comment by nbogojevic** [comment]
Not complete success. Starts correctly, but refresh fails. Now there are two different URLs one for refresh (wsbapi) and the old one for authentication https://account.withings.com. And it seems that the something is changed in payloads. I'd need to debug little bit more to see what is actually going on during oauth2 flow.

**Comment by Madj42** [comment]
If you guys need another tester, I'd be willing to have a go.  Unfortunately I haven't had the time to dedicate to adding python to my list of languages so I can't help there.

**Comment by Madj42** [comment]
BTW, the PR below and it's commits were never put in.  Vangorra had a bunch of changes to workaround some other bugs and the reauth bug supposedly.

https://github.com/home-assistant/core/pull/39684

**Comment by nbogojevic** [comment]
I've created PR #76 with fix.

**Comment by Madj42** [comment]
Can we run this though on our system without having to have it pull the API from pypi or wherever it pulls from?

**Comment by nbogojevic** [comment]
Might be complicated. I patched the library directly into home assistant.
If you can log in to shell of your Home Assistant container, then you could do following:

```shell
cd /usr/local/lib/python3.9/site-packages/withings_api
curl https://raw.githubusercontent.com/nbogojevic/python_withings_api/master/withings_api/__init__.py
```

**Comment by nbogojevic** [comment]
For info there probably needs to be another fix for Home Assistant component, but for the time being I don't have issue.

https://github.com/home-assistant/core/blob/b3cda6b6814703387e449068e8088f5b83880600/homeassistant/components/withings/__init__.py#L86-L87

**Comment by nbogojevic** [comment]
Created new pull request as #78 as changes in Withings response are not compatible with default behavior of `requests_oauthlib` and `oauthlib` and are breaking reauth flows.
