### ISSUE TITLE
[Feature][Help] Add support for air quality and room temperature

### ISSUE THREAD

**Issue by diogopms** [vangorra/python_withings_api#8]
Hey @vangorra, thanks for creating/supporting this lib and integrate with homeassistant.

I saw your PR in homeassistant GitHub and I'm testing until your branch until your PR gets merged.

I don't know if it's possible to add living room temperature and air quality (CO2) to the python lib and consequently in homeassistant component. 

Based on the https://healthmate.withings.com (I can see a chart with this information):

<img width="1679" alt="Screenshot 2019-10-19 at 22 13 33" src="https://user-images.githubusercontent.com/2445019/67151404-c63ae500-f2bd-11e9-8a13-327e02becd9f.png">

If my scale, can provide me with that information, I can use the other temperature sensor in other rom.

Thanks, best regards
Diogo

**Comment by diogopms** [comment]
I found the two fields on the codebase. 
Currently, it's saying Unknown but I will try to debug it...
Thanks

**Comment by diogopms** [comment]
The weight is working well, but no data on temperature room and CO2.

<img width="470" alt="Screenshot 2019-10-19 at 22 41 24" src="https://user-images.githubusercontent.com/2445019/67158360-07b7a880-f32f-11e9-972d-c02b77797af6.png">

**Comment by vangorra** [comment]
It doesn't appear the Withings Home camera is supported by their API. The API docs says `Using this API, developers have the ability to access data stored in the Health Mate app`. Withings Home uses a totally different app and presumably different (undocumented) API.
Additionally, it appears Withings has stopped all sales and development of the Home Camera project due to patent issues between Nokia/Apple (https://9to5mac.com/2017/03/13/withings-home-kit-home-plus-apple/). I doubt an API for this device will ever come.

**Comment by diogopms** [comment]
@vangorra thank you for your message.
I don't have a Withings Home camera. I'm using a simple Withings scale.
https://www.withings.com/us/en/scales

**Comment by vangorra** [comment]
Interesting. What settings did you set to give you co2? I don't see any option like that for my scale.

**Comment by diogopms** [comment]
Please check this gist with the curl request (I can't find any reference to this feature using oauth2 :( ).
https://gist.github.com/diogopms/20a0e5a2a73c273487f3eca3389550cd

I did the test using curl and get the AJAX request using a cookie, and it's working well.

Also, I'm doing a video showing the temperature sensor and CO2 sensor (air quality) trigger from my scale.

http://g.recordit.co/YrKLa2ra3S.gif

**Comment by diogopms** [comment]
If it's not available in the official api, we can close this issue. Thanks for all the support @vangorra 🙏

**Comment by vangorra** [comment]
I looked into this issue a big more. That is not part of the official API. It would be nice to have though.
